### ISSUE TITLE
Add --help argument

### ISSUE THREAD

**Issue by ubmit** [antfu/ni#101]
### Clear and concise description of the problem

As a user I want to have a --help argument so that I won't need to check the repo README file too often.

### Suggested solution

Add a --help argument to the CLI

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Wxh16144** [comment]
Nice, your suggestion is accepted, this issue should be closed. cc @antfu
