### ISSUE TITLE
[nr] Use `bun` for running scripts, if installed

### ISSUE THREAD

**Issue by aleclarson** [antfu/ni#107]
### Clear and concise description of the problem

[Bun](https://github.com/Jarred-Sumner/bun) is the fastest I've seen at running npm scripts.

### Suggested solution

Check for bun's existence and use it if possible

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I feel this could be a dangerous implicit move. If you use `bun.lockb`, `nr` will already run `bun` to execute. For other agents, I don't think the `npm run` `pnpm run` `yarn run` `bun` are 100% equivalent.
