### ISSUE TITLE
Custom commands support

### ISSUE THREAD

**Issue by RoyRao2333** [antfu/ni#109]
### Clear and concise description of the problem

Can ```ni``` support custom commands added by users?

For example, when I wanna add dependencies (not installing them) and there's no such command, I may wanna add my custom command (not very concise, just to demonstrate):

```pnpm add package-to-add``` -> ```nd package-to-add```
```pnpm add -D package-to-add``` -> ```ndd package-to-add```

### Suggested solution

> \# ~/.bashrc
> 
> \# custom configuration file path
> export NI_CONFIG_FILE="$HOME/.config/ni/nirc"

I've noticed that there's a custom configuration file can be added. Then maybe we can define our custom commands in that file?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You can use your shell's alias directly. Adding new command to `ni` is considered out-of-scope now.
