### ISSUE TITLE
Using '--help', also need to choose agent

### ISSUE THREAD

**Issue by smallnine9** [antfu/ni#110]
### Additional context

if we use` ni  -h` or `ni --help` in a folder where no lockfile exists, the ni also always let user choose an agent. may it's a little confused? because '--help'  show the ni's help docs, not related to agent.

**Comment by smallnine9** [comment]
[https://github.com/antfu/ni/blob/main/src/runner.ts#L48](url)
because in code we first get agent then run command, but maybe '--help' should not perform in this way?

**Comment by antfu** [comment]
PR welcome :)

**Comment by smallnine9** [comment]
alright, this is my PR #111 
hope I didn't make a mistake :)
