### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by andrefgneves** [antfu/ni#112]
### Clear and concise description of the problem

I would love it if I could fuzzy search the tasks when I don't provide one to `nr`.

### Suggested solution

I quickly grokked over the code and looks like you're using `prompts`, so something like [this](https://github.com/terkelg/prompts/issues/158) could help.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
PR welcome :)
