### ISSUE TITLE
Bug: ni 's package is wrong

### ISSUE THREAD

**Issue by Simon-He95** [antfu/ni#120]
### Describe the bug

<img width="554" alt="image" src="https://user-images.githubusercontent.com/57086651/207307364-cf4c42c0-2ff7-46d6-96ca-e4b45c87a6b3.png">

### Reproduction

remove local .lock file and execute ni

### System Info

```Shell
remove local .lock file and execute ni
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I can not reproduce it. #121 does not seem to be a correct fix to me, as you cd into a sub package, ni should always search up for the closest lock file that occurs.

**Comment by Simon-He95** [comment]
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/57086651/207433383-aa5274a3-73bb-477f-a7e5-e46da781a065.png">

if remove stopAt params ,the lockPath will not be in the current project.

steps to reproduce
1. delete .lock
2. run `esno ./src/commands/ni`

The "packageManager": "pnpm@7.4.0", but will use yarn to install the packages

**Comment by antfu** [comment]
You should not have a lock in your root outside of the project tbh. For the field, yes I think I should read it up for every package.json until we found one lock or the field.

**Comment by Simon-He95** [comment]
I think this is not the point, he should read the lock in my current directory instead of from my root directory
