### ISSUE TITLE
💡 Idea: `nx` command

### ISSUE THREAD

**Issue by nico-bachner** [antfu/ni#13]
`nx` could serve as the `ni` version of `npx`, `dlx`, and `pnpx`.

**Comment by nico-bachner** [comment]
Additional info:
- npm: [`npx`](https://docs.npmjs.com/cli/v7/commands/npx)
- yarn: [`dlx`](https://yarnpkg.com/cli/dlx)
- pnpm: [`pnpx`](https://pnpm.io/pnpx-cli)

**Comment by antfu** [comment]
I like it! Would you like to make a PR for it? Thanks!

**Comment by nico-bachner** [comment]
Sure thing.
