### ISSUE TITLE
the command not found after updated macos 

### ISSUE THREAD

**Issue by nasirDoe** [antfu/ni#142]
### Describe the bug

After i updated my macos ventura to version 13.2.1, the command of `ni` not found in my mac. Hope to fix earlier

### Reproduction

https://github.com/antfu/ni

### System Info

```Shell
Macos ventura: v13.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You should try install again
