### ISSUE TITLE
About `nix` - really reconsider renaming it

### ISSUE THREAD

**Issue by tunnckoCore** [antfu/ni#143]
About that https://github.com/antfu/ni#nx-is-no-longer-available

There's also `nix` OS and `nix` package manager, which is pretty serious and powerful thing - nixos.org

Or at least you should have a longer names for the commands too, so we can refer it from our aliases.

**Comment by antfu** [comment]
any better recommendation?

**Comment by JGJP** [comment]
`nlx`? `ndlx`? I don't use nix but was thinking the same thing

**Comment by real34** [comment]
As a nix user, I agree that the update is annoying.
Some suggestions: `nr -x`, `ndlx`, `ndo`, `nrr` (remote run)

**Comment by real34** [comment]
Thanks!
