### ISSUE TITLE
Ban likely-to-be-a-typo packages from being installed by `ni`

### ISSUE THREAD

**Issue by Dimava** [antfu/ni#146]
### Clear and concise description of the problem

I think people have typos like `ni add my-package`, or `ni add my-package`, or `ni i my-package` relatively often

Trying to install `add`, `install`, and `i` packages is clearly a mistake in those cases

### Suggested solution

- Installation of packages with same names as npm/yarn/pnpm commands have by `ni` should be prevented
- Installation of 1-letter and maybe 2-letter commands by `ni` should be prevented
- The **"`ni` can't install `${bannedPackageName}` because it's likely to be a typo"**-like error should be written to console
- The **"use `na install ${bannedPackageName}` if you actually want to install it"**-like suggestion should be written to console

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks, but this is not a goal of `ni`
