### ISSUE TITLE
`npm uninstall` / `yarn remove` 

### ISSUE THREAD

**Issue by vltansky** [antfu/ni#15]
Hey, what about `npm uninstall` / `yarn remove` command? Is it available?

**Comment by antfu** [comment]
What's the use case tho? I never use them, all I do is to remove the entry in package.json and `ni` again

**Comment by vltansky** [comment]
I find it faster. It will do both actions with one command.

**Comment by antfu** [comment]
Yeah, idk, just feel it's not that frequently used. I don't know if we should have every single command covered, but if you can find a good abbr for it (`nu` is taken, and `nun` is but unclear), I am fine receiving a PR for it. Thanks

**Comment by vltansky** [comment]
I'd be happy to submit a PR.
How about `nrm`? (rm=remove)

**Comment by antfu** [comment]
Alright, sound good, thanks!
