### ISSUE TITLE
Make it smart/compatible with rushjs

### ISSUE THREAD

**Issue by brunos3d** [antfu/ni#150]
### Clear and concise description of the problem

When used with rushjs-based monorepos the tool prompts every time for the target agent cause it couldn't find one of the agent files (yarn.lock, package-lock.json)

### Suggested solution

Make the tool lookup for the rush.json file then check what package manager rush uses by checking which one of [these options](https://rushjs.io/pages/maintainer/package_managers/#specifying-your-package-manager) are active on the config file

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
It's out-of-scope. I still belive you should use lock, or create a dummy package.json.
