### ISSUE TITLE
Support detect node version and change to the specified node version

### ISSUE THREAD

**Issue by SnowingFox** [antfu/ni#166]
### Clear and concise description of the problem

In this issue https://github.com/ant-design/antd-token-previewer, I encountered a problem and tried too many times, but still failed. Finally, the author told me that i should start it with node16, but i'm in node18.

This is really ridiculous, and i think there is a way to solve this problem?

Nodejs provide a configuration in package.json

```json
{
  "engines": {
    "node": ">=16.0.0 <17"
  }
}
```

But it just a declaration, it can't detect node version and most people will ignore this declaration when they execute install command, finally it will throw an error

so i think we can avoid this problem by using install scripts

### Suggested solution

```json
{
  "engines": {
    "node": ">=16.0.0 <17"
  }
}
```

when user execute
```bash
ni
```
ni will detect whether package.json configure this declaration or not, and change to the latest compatible version which user installed

we can use https://npmjs.com/n or nvm to change node version

### Alternative

Change the node version manually

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks. But it's out of scope of `ni`, which is just an alias. It might be better to find another tool to do so, and create your shell alias locally if you want it to be one command.
