### ISSUE TITLE
Support interactive updates to npm projects

### ISSUE THREAD

**Issue by gingermusketeer** [antfu/ni#168]
### Clear and concise description of the problem

NPM is not supported for interactive updates

### Suggested solution

Use https://www.npmjs.com/package/npm-check-updates to support this. 

### Additional context

This will help make a more consistent experience across tools

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
It's out-of-scope of ni. You can use `ncu` or [`taze`](https://github.com/antfu/taze) directly.
