### ISSUE TITLE
Release a docker image especially for the CI situation

### ISSUE THREAD

**Issue by LinuxSuRen** [antfu/ni#177]
### Clear and concise description of the problem

I want to use `ni` in my CI environment. But I'm thinking about if it's reasonble to avoid run `npm i -g @antfu/ni` everytime. Instead, having a docker image which already consist `ni`.

### Suggested solution

Provide a Dockerfile. Build and push the image to ghcr.io via GitHub Actions.

I'd be happy to help on this if the active maintainers believe it's ok.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for bringing this up. But sorry as I don't use Docker myself, I'll leave that to the community to build and maintian.

**Comment by LinuxSuRen** [comment]
Please see also the following project if there is anyone have the same use cases.

https://github.com/LinuxSuRen/antfu-ni-docker
