### ISSUE TITLE
Enhancement for non-interactive use cases

### ISSUE THREAD

**Issue by LinuxSuRen** [antfu/ni#178]
### Clear and concise description of the problem

For non-interaceive use cases, it would be great if there is a flag to skip any potential prompt. For instance, it will let user to do the following choice if the `pnpm` does not exist:

* `Would you like to globally install pnpm?`

In the CI situation, usually there is no user interactives.

### Suggested solution

Please feel free to see also the following example usage:

```shell
ni -i=false # -i means --interactive
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by LinuxSuRen** [comment]
In my case, I wish `ni` could install an agent automatically. So, how to set `autoInstall`?

**Comment by antfu** [comment]
You can run `nci` which installs agent automatically

**Comment by LinuxSuRen** [comment]
This is what I need. Thanks for your help.
