### ISSUE TITLE
New installation method that does not rely on NPM, can be installed and upgraded independently.

### ISSUE THREAD

**Issue by baboon-king** [antfu/ni#181]
### Clear and concise description of the problem

When we use a Node version manager (such as nvm, fnm) and have multiple Node versions on our computer, installing `@antfu/ni` using `npm i -g @antfu/ni` will install it in the global package of the currently active npm. This can lead to several issues.

1. When switching Node versions and running npm list -g, @antfu/ni will not be listed (although it can still be used as a global package). This can cause ambiguity.
2. Updating @antfu/ni becomes problematic. Due to the switched Node version, the package does not exist, resulting in an inability to update it, requiring a reinstallation.

### Suggested solution

Provide additional installation methods, similar to [PNPM Using a standalone script](https://pnpm.io/installation#using-a-standalone-script)

### Alternative

When I use the standalone installation of `PNPM` to install (`pnpm i @antfu/ni -g`), `@antfu/ni` can achieve this effect, but it depends on the standalone installation of PNPM.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
After all, `ni` is a node package and works for node package managers. The problem occurs to any globally installed packages, it's more like a limitation/design choice of Node.js and the Node version manager. I don't think we would do anything about it as this is how it works. Thanks for bringing this up tho.

**Comment by baboon-king** [comment]
> [After all, `ni` is a node package......](https://github.com/antfu/ni/issues/181#issuecomment-1803695407)

Ok. right! 
Thank you for your reply and answer!
