### ISSUE TITLE
Is  globalAgent always use npm when  run  'ni -g xxx' in project workspace?

### ISSUE THREAD

**Issue by aswind7** [antfu/ni#183]
when i run 'ni -g xxx' in a project workspace i see it always use npm,  then i see the source code of src/config.ts.
I think it always excute `      config = { ...defaultConfig, defaultAgent: agent }`  because agent always exists. And i want to know  is it so? thanks.

```
export async function getConfig(): Promise<Config> {
  if (!config) {
    const agent = await detect({ programmatic: true })
    if (agent)
      config = { ...defaultConfig, defaultAgent: agent }
    else
      config = Object.assign({}, defaultConfig, ini.parse(fs.readFileSync(rcPath, 'utf-8')))
  }

  return config
}
```

**Comment by antfu** [comment]
<img width="578" alt="image" src="https://github.com/antfu/ni/assets/11247099/20dfb840-1842-40b9-bafa-bede7c2c6f14">
<img width="511" alt="image" src="https://github.com/antfu/ni/assets/11247099/bb48d0da-83c1-4d97-961a-1318ba810554">
