### ISSUE TITLE
Support load config in ~/.config/.nirc

### ISSUE THREAD

**Issue by CoolPlayLin** [antfu/ni#195]
### Clear and concise description of the problem

As a user, I'd like every CLI's config file can put in a folder like `~/.config` instead of putting on user's root folder. It would make my root folder mess and inconvenient to manage.

### Suggested solution

Currently, ni only read config in `~/` . I hope that you could path in `~/.config`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by HawtinZeng** [comment]
Hi, bro, I have find a way to automatically read nirc file from the custom path, just use Environment Variable, If your machine is based on windows, you can follow this blog.

**Comment by kitschpatrol** [comment]
I think based on the [readme](https://github.com/antfu/ni#config), you can "just" add this to your shell rc to use a custom configuration file path?

```sh
# ~/.bashrc

# custom configuration file path
export NI_CONFIG_FILE="$HOME/.config/ni/nirc"
```
