### ISSUE TITLE
asdf plugin

### ISSUE THREAD

**Issue by CanRau** [antfu/ni#198]
### Clear and concise description of the problem

Would love to be able to manage `ni` via [asdf](https://asdf-vm.com)

### Suggested solution

create asdf plugin https://asdf-vm.com/plugins/create.html

### Alternative

Homebrew, though out of scope according to https://github.com/antfu/ni/issues/91#issuecomment-1191070355 so asdf might be as well

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for bringing this up, but I have no interest in doing so. I guess it might be possible to do as a community project.

**Comment by CanRau** [comment]
Actually created it couple of weeks ago https://github.com/CanRau/asdf-ni
Should this be added to the readme @antfu?

**Comment by antfu** [comment]
Cool! Ofc, PR welcome :)
