### ISSUE TITLE
What's the result if both lock files exists?

### ISSUE THREAD

**Issue by vivaxy** [antfu/ni#2]
Same issue as `yarn-or-npm`, see discussions in https://github.com/camacho/yarn-or-npm/issues/6.

**Comment by antfu** [comment]
'pnpm-lock.yaml' > 'yarn.lock' > 'package-lock.json'

Does this make sense to you? Tho I would say you shouldn't have both lockfiles exists and this tool is trying to prevent you accidentally create them.
