### ISSUE TITLE
Support JSR

### ISSUE THREAD

**Issue by tmg0** [antfu/ni#206]
### Clear and concise description of the problem

Maybe support `jsr` as a agent ?

### Suggested solution

Add a field named `packageRegistry` in `package.json` ?

And if declared the `packageRegistry` as `jsr`, `ni` will run the command `jsr add` with right package manager like `npx jsr add`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
> packageRegistry in package.json

Is this something in the standard? If not I don't think we should invent it.

I am not sure about this feature in general, we the tools we have right now. JSR packages can coexists with NPM packages, and `ni` is for package clients not registry.
