### ISSUE TITLE
[Idea] Include `taze` with `ni`

### ISSUE THREAD

**Issue by innocenzi** [antfu/ni#22]
I use https://github.com/antfu/taze quite frequently and just thought it would quite fall under the scope of this project, that is, managing dependencies easily with one tool and unified syntax. 

One could argue that `ni`'s scope should stay limited. I won't open the debate but I wanted to submit the idea. A `nt` command would be pretty cool.

**Comment by antfu** [comment]
Thanks for bringing this up. But probably won't as I think the command `taze` is already short enough and it might also be out-of-scope with `ni` trying to solve (unified package managers). If you want, you can always set the alias in your shell.

**Comment by innocenzi** [comment]
Makes sense, that's the answer I expected. I can alias it indeed, my concern was more about not having to think about updating it. It's fine anyway!, was just a random idea. :)
