### ISSUE TITLE
[Feature] add outdated packages list output

### ISSUE THREAD

**Issue by DrJume** [antfu/ni#35]
As with `nu -i`, add an option for listing outdated packages.
This would be an alias for `npm outdated`, `pnpm outdated` and `yarn outdated`.

Example: `nu -o`

Thank you for this very helpful tool! ❤️

**Comment by nberlette** [comment]
@DrJume First off, sorry for digging up an old issue! I'm experimenting with extending the existing commands in a fork I've created at https://github.com/nberlette/n (published as `@brlt/n` on npm). One of several new commands is `no`, which lists outdated dependencies via `<npm|pnpm|yarn> outdated`.  

If you're able to check it out by any chance, your opinion will help quite a bit with moving towards a PR for it here. Thanks!

**Comment by antfu** [comment]
We recently introduced a new `na` command for aliasing agents purely. So you could run `na outdated` for that. And if you prefer, you can set the alias to rename it to `no` or anything you want in your local shell.

```sh
alias no="na outdated"
```
