### ISSUE TITLE
bug: Executing ni under window, ni cannot be executed because there is a command similar to ni in the system.

### ISSUE THREAD

**Issue by littleCareless** [antfu/ni#39]
As described in the title.
My system is window 10 20h2.
My ni version is 0.10.1.
The output after executing ni is as follows.
`PS C:\Users\xxxxx> ni

位于命令管道位置 1 的 cmdlet New-Item
请为以下参数提供值:
Path[0]:`

**Comment by antfu** [comment]
#33
