### ISSUE TITLE
Respect volta npm and yarn paths

### ISSUE THREAD

**Issue by knownasilya** [antfu/ni#43]
https://volta.sh sets custom paths per project. NI does not respect these paths, and uses the global node/npm/yarn installed by volta not the project specific one.

**Comment by antfu** [comment]
I don't use Volta myself. If it's easy to support I am happy to receive a PR for it. Thanks

**Comment by posva** [comment]
This is fixed now :+1:

**Comment by knownasilya** [comment]
😎 nice, thanks!

**Comment by satouriko** [comment]
AFAIK, volta shims `npm` and `yarn` global command to `volta-shim` and select the correct version as per the project. So why is it necessary to call `volta run` directly? This breaks using corepack with volta: https://github.com/volta-cli/volta/issues/987#issuecomment-914502143
