### ISSUE TITLE
Windows platform: Conflicts with PowerShell New-Item alias.

### ISSUE THREAD

**Issue by muzaisimao** [antfu/ni#47]
View current PowerShell version: run  `get-host | select version`

---

Version: `5.x`

1. Open folder: `C:\Windows\System32\WindowsPowerShell\v1.0`

2. Edit file: `Microsoft.PowerShell_profile.ps1` - If the file does not exist, create a new one.

3. Add the following line to the end of the file: `Del alias:ni -Force`

4. Restart the terminal.

---

Version: `7.x`

1. Open folder: `C:\Program Files\PowerShell\7`

2. Edit file: `Microsoft.PowerShell_profile.ps1` - If the file does not exist, create a new one.

3. Add the following line to the end of the file: `Remove-Alias -Name ni -Force`

4. Restart the terminal.

**Comment by muzaisimao** [comment]
This is a known issue and has been discussed in #21 and #33. 
Since most users are still in PowerShell 5.x, more detailed steps are released.

**Comment by lizy0329** [comment]
I'm so crazy that change my system config for a lib

**Comment by antfu** [comment]
Thanks! I have including them in the readme.
