### ISSUE TITLE
bug: `nr ` lost `npm_config_` env

### ISSUE THREAD

**Issue by qiwang97** [antfu/ni#55]
`nr` add additional `--`  in `src/agents.ts ` and therefore  [npm config env](https://docs.npmjs.com/cli/v7/using-npm/config) is lost.

```bash
➜  nr dev --report
✔ Choose the agent › npm

> ni-lost-npm-config@0.0.1 dev
> node ./index.js "--report"

npm_config_report undefined


➜ npm run dev --report

> ni-lost-npm-config@0.0.1 dev
> node ./index.js

npm_config_report true
```

**Comment by coder-lcn** [comment]
不太明白，是 nr dev --report 没有打印 npm 的 config 信息？

**Comment by qiwang97** [comment]
> 不太明白，是 nr dev --report 没有打印 npm 的 config 信息？

npm run dev --report 会注入 npm_config_report=true
但是 nr dev --report 时 npm_config_report 是 undefined，环境变量丢了

**Comment by coder-lcn** [comment]
> > 不太明白，是 nr dev --report 没有打印 npm 的 config 信息？
> 
> npm run dev --report 会注入 npm_config_report=true 但是 nr dev --report 时 npm_config_report 是 undefined，环境变量丢了

啊，原来是这样，谢谢你

**Comment by Wxh16144** [comment]
看了一圈源码，发现 `nr dev --report` 等同于 `npm run dev -- --report`;

`--` 的功能，具体可以参考这里 https://github.com/npm/npm/pull/5518；


<img width="1512" alt="image" src="https://user-images.githubusercontent.com/32004925/165922578-a42abac4-6296-407a-ba61-cd9dda349c96.png">

**Comment by antfu** [comment]
I think this is how `nr` is defined to be. It forwards all options to the script instead of `npm`.
