### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by denniarems** [antfu/ni#61]
![image](https://user-images.githubusercontent.com/39432770/153652871-4ba567a6-e0eb-4395-bd4f-f837359685ae.png)

Permission denied while running nr i, after installing @antfu/ni globally.

**Comment by luvletterldl** [comment]
> ![image](https://user-images.githubusercontent.com/39432770/153652871-4ba567a6-e0eb-4395-bd4f-f837359685ae.png)
> 
> Permission denied while running nr i, after installing @antfu/ni globally.

`missing script i`， if you want install dependencies, you should exec `ni`, if you want run some script cmd, you should exec `nr your script`, eg: `nr dev`, `nr start`

**Comment by antfu** [comment]
This is probably not an issue of ni itself.

**Comment by RennCheung** [comment]
I encountered this problem after upgrading Node, running the following command to solve this problem:
```bash
sudo npm cache clean --force --unsafe-perm
```
https://stackoverflow.com/a/57268608/16248512
