### ISSUE TITLE
[feature request] no - npm outdated

### ISSUE THREAD

**Issue by rchl** [antfu/ni#62]
New command `no` for `npm outdated` / `yarn outdated`

**Comment by Wxh16144** [comment]
Maybe you can try `na outdated`;  af19dc0e626ed9706ba28883000b47685f494af2

**Comment by rchl** [comment]
That would save 1 character only. :)
And I wouldn't be able to use the shortcut `out` which works for `npm` but not `yarn`.

**Comment by antfu** [comment]
We longer accept new cli entries. See
https://github.com/antfu/ni/issues/35#issuecomment-1120488510
