### ISSUE TITLE
[feature request]: nid - npm install --dev

### ISSUE THREAD

**Issue by adenvt** [antfu/ni#67]
Add `nid` alias for `npm install --dev` or `yarn add --dev`

**Comment by antfu** [comment]
I use `ni -D` and I feel that it's too much to type tbh

**Comment by coder-lcn** [comment]
> Add `nid` alias for `npm install --dev` or `yarn add --dev`

Perhaps, you can set an alias in the terminal for this

**Comment by adenvt** [comment]
> > Add `nid` alias for `npm install --dev` or `yarn add --dev`
> 
> Perhaps, you can set an alias in the terminal for this

This nice solution, thank
