### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by unlight** [antfu/ni#8]
Looks like it does not work on Windows.

```sh
pnpm -v # => 5.13.4
ni
```
Result
```
'command' is not recognized as an internal or external command,
operable program or batch file.
Detected pnpm but it doesn't seem to be installed.
```

**Comment by antfu** [comment]
I don't use Windows recently but I found this: https://stackoverflow.com/questions/27392680/how-to-determine-if-a-command-exists-on-windows

Can you modify the code and try out to see if it works and maybe send a PR? Much apperciated.

**Comment by unlight** [comment]
I replaced
```
_child_process.execSync.call(void 0, `command -v ${cmd}`);
```
by
```
_child_process.execSync.call(void 0, `cmd /c "(help ${cmd} > nul || exit 0) && where ${cmd} > nul 2> nul"`);
```
and it did the trick. No errors.

**Comment by antfu** [comment]
Thanks. Supported in v0.2.3
