### ISSUE TITLE
alternative solution for alias conflicts with PowerShell on Windows

### ISSUE THREAD

**Issue by ivanhofer** [antfu/ni#81]
I tried out the solution described at the bottom of the README. It didn't work.
~By running following command in PowerShell 7, I could get rid of the system alias:~
~`del alias:ni -Force`~
~The `-Force` flag is needed because it is a system alias that is protected.~
Edit: the solution above is only valid for the current session.

The following solution worked:
1. create powershell profile file:
```ps
New-Item $profile -force -itemtype file
```

2. open file:
```ps
notepad $profile
```

3. add following line:
```
remove-item alias:ni -Force
```

4. safe file and open new PowerShell

**Comment by itpropro** [comment]
This would overwrite your existing PowerShell profile and is definitely not recommended.
If you want to co conditionally add this to your profile, you should consider something like this:

```PowerShell
if (-not (Test-Path $profile)) {
  New-Item -ItemType File -Path (Split-Path $profile) -Force -Name (Split-Path $profile -Leaf)
}

$profileEntry = 'Remove-Item Alias:ni -Force -ErrorAction Ignore'
$profileContent = Get-Content $profile
if ($profileContent -notcontains $profileEntry) {
  $profileEntry | Out-File $profile -Append -Force
}
```

**Comment by antfu** [comment]
If there is any improvement could make to the current docs, feel free to PR. I am not familiar with PowerShell to judge/help here.
