### ISSUE TITLE
`.nirc` `globalAgent` flag doesn't seem to work.

### ISSUE THREAD

**Issue by mrwwalmsley** [antfu/ni#82]
I have a `.nirc` file in the same directory as my package.json, but the `globalAgent` is ignored when installing global packages, and is using `npm` instead of `pnpm`.

Here is the contents of my `.nirc` file:

```
defaultAgent=pnpm
globalAgent=pnpm
```

**Comment by antfu** [comment]
.nirc has to be under your home directory `~/.nirc`

**Comment by katemanx** [comment]
PowerShell 7 已删除别名 运行ni命令 还是出现异常报错
![image](https://user-images.githubusercontent.com/50615728/177277301-4f9667d8-fda7-462d-949b-8624b86a32d1.png)

**Comment by mrwwalmsley** [comment]
Is it possible to read from the NPM package so we could commit to GIT.
Was trying to make it as easy as possible for the whole team to switch to PNPM.

**Comment by antfu** [comment]
> Is it possible to read from the NPM package so we could commit to GIT?

We could have a `ni` field in package.json.

> I assumed/hoped that nt would run npm test. Is there any reason you couldn't add that shortcut?

You can set your local alias. See https://github.com/antfu/dotfiles/blob/main/.zshrc#L23-L37
