### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by yzh990918** [antfu/ni#86]
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/46418596/177975017-621b561c-3bbf-4567-8f4f-5f39ef233aca.png">

**Comment by mewcoder** [comment]
`sudo chown -R $(whoami) /usr/local/lib/node_modules`

**Comment by JGJP** [comment]
imo this is not a solution. I encounter this error pretty often and my question is why does this happen in the first place?
