### ISSUE TITLE
[FEATURE REQUEST] Add an option to use Bun as default executable

### ISSUE THREAD

**Issue by eggsy** [antfu/ni#87]
Hey there! Team behind Bun.js has finally released their first (beta) version, it's not available for Windows (without WSL) but seems like it runs smoothly on any other platform at the moment. I use `nr` and `ni` a lot but since I want to move to Bun, I always type `bun run dev` etc.. So, it'd be great to have an option/toggle to choose what `nr` defaults to, even when there's a different package manager because I still use `pnpm` as my main package manager.

**Comment by antfu** [comment]
Yeah I am happy to have it. PR is also welcome!
