### ISSUE TITLE
Support brew tool installation

### ISSUE THREAD

**Issue by cy920820** [antfu/ni#91]
### Clear and concise description of the problem

Hope to support brew package manager

### Suggested solution

Hope to support brew package manager

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for bringing this up. But brew is probably out-of-scope as a node package manager.
