### ISSUE TITLE
可执行文件 是 .mjs  那为什么还编译 .cjs 文件

### ISSUE THREAD

**Issue by hipi** [antfu/ni#92]
### Clear and concise description of the problem

一开始 我想在nodejs 10 使用的 发现可执行文件是 `.mjs`  ,nodejs 10 并不支持，但又发现 编译后 的 `dist` 文件夹编译了`.cjs` 文件

### Suggested solution

- 问题1 是否支持nodejs 10
- 问题2 如不支持 或许可以在 不编译cjs
  ```js
    rollup: {
    emitCJS: false,
    inlineDependencies: true,
  }
  ```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
For programmatic usage.
